[workspace]
resolver = "2"
members = [
    "kermit-algos",
    "kermit-ds",
    "kermit-iters"
]

[workspace.package]
description = "Kermit, the Leapfrog Triejoin algorithm with associated data structures"
version = "0.0.1-dev"
authors = ["Aidan Bailey"]
edition = "2021"
homepage = "https://github.com/aidan-bailey/kermit"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/aidan-bailey/kermit"
