[package]
name = "rs-trie"
version = "0.0.1"
edition = "2021"
authors = ["Aidan Bailey"]
description = "A simple Trie data structure implementation"
readme = "README.md"
repository = "https://github.com/aidan-bailey/rs-trie"
license = "MIT OR Apache-2.0"

[dependencies]
