array_width=60
attr_fn_like_width=70
binop_separator="Front"
blank_lines_lower_bound=0
blank_lines_upper_bound=1
brace_style="SameLineWhere"
chain_width=60
color="Auto"
combine_control_expr=true
comment_width=80
condense_wildcard_suffixes=true
control_brace_style="AlwaysSameLine"
disable_all_formatting=false #?
edition="2015"
empty_item_single_line=true
enum_discrim_align_threshold=0
error_on_line_overflow=false
error_on_unformatted=false
fn_call_width=60
fn_params_layout="Compressed" # "Tall"
fn_single_line=true # false
force_explicit_abi=true
force_multiline_blocks=false
format_code_in_doc_comments=true # false
doc_comment_code_block_width=100
format_generated_files=true
generated_marker_line_search_limit=3
format_macro_matchers=true # false
format_macro_bodies=true
skip_macro_invocations=[]
format_strings=true # false
hard_tabs=false
hex_literal_case="Preserve"
show_parse_errors=true
# ignore=
imports_indent="Block"
imports_layout="Mixed"
indent_style="Block"
inline_attribute_width=0
match_arm_blocks=true
match_arm_leading_pipes="Always" # "Never"
match_block_trailing_comma=true # false
max_width=100
merge_derives=true
imports_granularity="One" # "Preserve"
newline_style="Auto"
normalize_comments=true # false
normalize_doc_attributes=true # false
overflow_delimited_expr=true # false
remove_nested_parens=true
reorder_impl_items=true # false
reorder_imports=true
group_imports="StdExternalCrate" # "Preserve"
reorder_modules=true
#required_version="CARGO_PKG_VERSION"
short_array_element_width_threshold=10
skip_children=false
single_line_if_else_max_width=0 # 50
single_line_let_else_max_width=0 # 50
space_after_colon=true
space_before_colon=false
spaces_around_ranges=false
struct_field_align_threshold=0
struct_lit_single_line=false # true
struct_lit_width=18
struct_variant_width=35
#style_edition="2015"
tab_spaces=4
trailing_comma="Vertical"
trailing_semicolon=true
type_punctuation_density="Wide"
unstable_features=true # false
use_field_init_shorthand=true # false
use_small_heuristics="Default"
use_try_shorthand=true # false
where_single_line=false
wrap_comments=true # false
