[package]
name = "kermit-iters"
description.workspace = true
version = "0.0.2-dev"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true

[dependencies]
