//! Integration tests for the `#[derive(IntoTrieIter)]` proc macro.
//!
//! These tests verify that the generated `IntoIterator` impl correctly wraps a
//! `TrieIterator` in a `TrieIteratorWrapper` and produces the expected tuples.

use kermit_iters::{LinearIterator, TrieIterator, TrieIteratorWrapper};

// -- Minimal mock trie for testing the derive macro --

struct MockNode {
    key: usize,
    children: Vec<MockNode>,
}

fn leaf(key: usize) -> MockNode {
    MockNode {
        key,
        children: vec![],
    }
}

fn node(key: usize, children: Vec<MockNode>) -> MockNode {
    MockNode { key, children }
}

struct MockTrie {
    roots: Vec<MockNode>,
}

struct MockLevel<'a> {
    siblings: &'a [MockNode],
    pos: usize,
}

/// A minimal trie iterator that derives `IntoTrieIter`.
#[derive(kermit_derive::IntoTrieIter)]
struct MockTrieIter<'a> {
    trie: &'a MockTrie,
    levels: Vec<MockLevel<'a>>,
}

impl<'a> MockTrieIter<'a> {
    fn new(trie: &'a MockTrie) -> Self {
        MockTrieIter {
            trie,
            levels: Vec::new(),
        }
    }
}

impl LinearIterator for MockTrieIter<'_> {
    fn key(&self) -> Option<usize> {
        let level = self.levels.last()?;
        level.siblings.get(level.pos).map(|n| n.key)
    }

    fn next(&mut self) -> Option<usize> {
        let level = self.levels.last_mut()?;
        level.pos += 1;
        level.siblings.get(level.pos).map(|n| n.key)
    }

    fn seek(&mut self, seek_key: usize) -> bool {
        if let Some(level) = self.levels.last_mut() {
            while level.pos < level.siblings.len() {
                if level.siblings[level.pos].key >= seek_key {
                    return true;
                }
                level.pos += 1;
            }
        }
        false
    }

    fn at_end(&self) -> bool {
        match self.levels.last() {
            | Some(level) => level.pos >= level.siblings.len(),
            | None => true,
        }
    }
}

impl TrieIterator for MockTrieIter<'_> {
    fn open(&mut self) -> bool {
        if self.levels.is_empty() {
            if self.trie.roots.is_empty() {
                return false;
            }
            self.levels.push(MockLevel {
                siblings: &self.trie.roots,
                pos: 0,
            });
            true
        } else {
            let level = self.levels.last().unwrap();
            if level.pos >= level.siblings.len() {
                return false;
            }
            let node = &level.siblings[level.pos];
            if node.children.is_empty() {
                return false;
            }
            self.levels.push(MockLevel {
                siblings: &node.children,
                pos: 0,
            });
            true
        }
    }

    fn up(&mut self) -> bool {
        self.levels.pop().is_some()
    }
}

#[test]
fn derive_generates_into_iterator() {
    let trie = MockTrie {
        roots: vec![node(1, vec![leaf(2), leaf(3)]), node(4, vec![leaf(5)])],
    };
    let iter = MockTrieIter::new(&trie);
    // into_iter() is generated by #[derive(IntoTrieIter)]
    let result: Vec<Vec<usize>> = iter.into_iter().collect();
    assert_eq!(result, vec![vec![1, 2], vec![1, 3], vec![4, 5]]);
}

#[test]
fn derive_empty_trie() {
    let trie = MockTrie { roots: vec![] };
    let iter = MockTrieIter::new(&trie);
    let result: Vec<Vec<usize>> = iter.into_iter().collect();
    assert!(result.is_empty());
}

#[test]
fn derive_into_iter_type_is_wrapper() {
    let trie = MockTrie {
        roots: vec![leaf(42)],
    };
    let iter = MockTrieIter::new(&trie);
    // Verify the type is TrieIteratorWrapper (this is a compile-time check —
    // if the derive generated a different IntoIter type, this wouldn't compile)
    let wrapper: TrieIteratorWrapper<MockTrieIter<'_>> = iter.into_iter();
    let result: Vec<Vec<usize>> = wrapper.collect();
    assert_eq!(result, vec![vec![42]]);
}
