//! End-to-end correctness check for the WatDiv pipeline.
//!
//! Loads a small fixture (pre-generated by the Python preprocessor and
//! committed under `tests/fixtures/watdiv-mini/artifacts/`) and runs
//! every query from the emitted YAML against the committed Parquet
//! relations, comparing tuple counts to the hand-verified
//! `expected.json`. Exercises the full Const-view rewrite path in
//! [`lftj_join`] without any network or Python dependency at test time.
//! Every query runs under every optimiser, because a plan changes the
//! descent order, never the answer.

use {
    clap::ValueEnum,
    kermit::db::{lftj_join, Database, SortedFamily},
    kermit_algos::{ColumnOrderPolicy, JoinQuery, LeapfrogTriejoin, Optimiser, Planner},
    kermit_bench::BenchmarkDefinition,
    kermit_ds::{
        BinarySeek, Cardinality, ColumnTrie, GallopingSeek, LinearSeek, Relation, RelationFileExt,
        TreeTrie,
    },
    kermit_iters::TrieIterable,
    std::{
        collections::{BTreeMap, HashMap},
        path::{Path, PathBuf},
    },
};

fn artifacts_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/watdiv-mini/artifacts")
}

fn load_yaml(dir: &Path) -> BenchmarkDefinition {
    let yaml = std::fs::read_to_string(dir.join("watdiv-stress-mini-tiny.yml"))
        .expect("fixture YAML missing");
    serde_yaml::from_str(&yaml).expect("fixture YAML malformed")
}

fn load_expected(dir: &Path) -> HashMap<String, usize> {
    let json = std::fs::read_to_string(dir.join("expected.json")).expect("expected.json missing");
    serde_json::from_str(&json).expect("expected.json malformed")
}

/// Loads the fixture's relations as `R` and checks every query's result
/// count, planned by `optimiser`, against `expected.json`.
fn check_cardinalities<R: TrieIterable + Relation + Cardinality>(optimiser: Optimiser) {
    let dir = artifacts_dir();
    let bench = load_yaml(&dir);
    let expected = load_expected(&dir);

    let mut relations: BTreeMap<String, R> = BTreeMap::new();
    for rel in &bench.relations {
        let path = dir.join(format!("{}.parquet", rel.name));
        let trie =
            R::from_parquet(&path).unwrap_or_else(|e| panic!("failed to load {path:?}: {e}"));
        relations.insert(rel.name.clone(), trie);
    }
    let planner = Planner::new(optimiser.instantiate(), ColumnOrderPolicy::Stored);
    let relations = Database::new::<SortedFamily>(relations, planner.required_statistics());

    for q in &bench.queries {
        let key = format!("{}::{}", bench.name, q.name);
        let want = *expected
            .get(&key)
            .unwrap_or_else(|| panic!("no expected entry for {key}"));

        let parsed: JoinQuery = q.query.parse().expect("datalog parse failure");
        let got = lftj_join::<R, LeapfrogTriejoin>(&relations, parsed, &planner)
            .unwrap_or_else(|e| panic!("query {}: {e}", q.name))
            .len();

        assert_eq!(
            got,
            want,
            "cardinality mismatch on {key} ({} / {}): got {got}, expected {want}\nquery: {}",
            optimiser.axis_value(),
            std::any::type_name::<R>(),
            q.query
        );
    }
}

#[test]
fn watdiv_mini_cardinalities_match() {
    // The plan an optimiser picks changes the descent order, never the
    // answer; iterating the CLI enum covers optimisers added later.
    for &optimiser in Optimiser::value_variants() {
        check_cardinalities::<TreeTrie<LinearSeek>>(optimiser);
        check_cardinalities::<TreeTrie<BinarySeek>>(optimiser);
        check_cardinalities::<TreeTrie<GallopingSeek>>(optimiser);
        check_cardinalities::<ColumnTrie<LinearSeek>>(optimiser);
        check_cardinalities::<ColumnTrie<BinarySeek>>(optimiser);
        check_cardinalities::<ColumnTrie<GallopingSeek>>(optimiser);
    }
}
