//! End-to-end correctness check for the WatDiv pipeline.
//!
//! Loads a small fixture (pre-generated by the Python preprocessor and
//! committed under `tests/fixtures/watdiv-mini/artifacts/`) and runs
//! every query from the emitted YAML against the committed Parquet
//! relations, comparing tuple counts to the hand-verified
//! `expected.json`. Exercises the full Const-view rewrite path in
//! `kermit::db::lftj_join` without any network or Python dependency at test
//! time. Every query runs under every optimiser and column-order policy,
//! because a plan changes the descent order, and under `--column-orders any`
//! the atoms it reads through reordered copies, never the answer.

mod common;

use {
    clap::ValueEnum,
    common::utils::{join_under_planner, load_parquet_relations, JoinEntry},
    kermit_algos::{ColumnOrderPolicy, JoinQuery, LeapfrogTriejoin, Optimiser, Planner},
    kermit_bench::BenchmarkDefinition,
    kermit_ds::{
        BinarySeek, Cardinality, ColumnTrie, GallopingSeek, LinearSeek, Relation, TreeTrie,
    },
    kermit_iters::TrieIterable,
    std::{
        collections::HashMap,
        path::{Path, PathBuf},
    },
};

fn artifacts_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/watdiv-mini/artifacts")
}

fn load_yaml(dir: &Path) -> BenchmarkDefinition {
    let yaml = std::fs::read_to_string(dir.join("watdiv-stress-mini-tiny.yml"))
        .expect("fixture YAML missing");
    serde_yaml::from_str(&yaml).expect("fixture YAML malformed")
}

fn load_expected(dir: &Path) -> HashMap<String, usize> {
    let json = std::fs::read_to_string(dir.join("expected.json")).expect("expected.json missing");
    serde_json::from_str(&json).expect("expected.json malformed")
}

/// Loads the fixture's relations as `R` and checks every query's result
/// count, planned by `optimiser` under `policy`, against `expected.json`.
fn check_cardinalities<R: TrieIterable + Relation + Cardinality>(
    optimiser: Optimiser, policy: ColumnOrderPolicy,
) {
    let dir = artifacts_dir();
    let bench = load_yaml(&dir);
    let expected = load_expected(&dir);

    let (relations, inputs) =
        load_parquet_relations::<R>(&dir, bench.relations.iter().map(|r| r.name.as_str()));
    let planner = Planner::new(optimiser.instantiate(), policy);
    let mut database =
        <LeapfrogTriejoin as JoinEntry<R>>::database(relations, planner.required_statistics());

    for q in &bench.queries {
        let key = format!("{}::{}", bench.name, q.name);
        let want = *expected
            .get(&key)
            .unwrap_or_else(|| panic!("no expected entry for {key}"));

        let parsed: JoinQuery = q.query.parse().expect("datalog parse failure");
        let (rows, _) =
            join_under_planner::<R, LeapfrogTriejoin>(&mut database, &inputs, parsed, &planner)
                .unwrap_or_else(|e| panic!("query {}: {e}", q.name));
        let got = rows.len();

        assert_eq!(
            got,
            want,
            "cardinality mismatch on {key} ({} / {} / {}): got {got}, expected {want}\nquery: {}",
            optimiser.axis_value(),
            policy.axis_value(),
            std::any::type_name::<R>(),
            q.query
        );
    }
}

#[test]
fn watdiv_mini_cardinalities_match() {
    // The plan an optimiser picks changes the descent order, never the
    // answer; iterating the CLI enum covers optimisers added later.
    for &policy in ColumnOrderPolicy::value_variants() {
        for &optimiser in Optimiser::value_variants() {
            check_cardinalities::<TreeTrie<LinearSeek>>(optimiser, policy);
            check_cardinalities::<TreeTrie<BinarySeek>>(optimiser, policy);
            check_cardinalities::<TreeTrie<GallopingSeek>>(optimiser, policy);
            check_cardinalities::<ColumnTrie<LinearSeek>>(optimiser, policy);
            check_cardinalities::<ColumnTrie<BinarySeek>>(optimiser, policy);
            check_cardinalities::<ColumnTrie<GallopingSeek>>(optimiser, policy);
        }
    }
}
