//! End-to-end correctness check for the WatDiv pipeline.
//!
//! Loads a small fixture (pre-generated by the Python preprocessor and
//! committed under `tests/fixtures/watdiv-mini/artifacts/`) and runs
//! every query from the emitted YAML against the committed Parquet
//! relations, comparing tuple counts to the hand-verified
//! `expected.json`. Exercises the full Const-view rewrite path in
//! [`lftj_join`] without any network or Python dependency at test time.

use {
    kermit::db::lftj_join,
    kermit_algos::{JoinQuery, LeapfrogTriejoin, LexicographicOptimiser},
    kermit_bench::BenchmarkDefinition,
    kermit_ds::{RelationFileExt, TreeTrie},
    std::{
        collections::{BTreeMap, HashMap},
        path::{Path, PathBuf},
    },
};

fn artifacts_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/watdiv-mini/artifacts")
}

fn load_yaml(dir: &Path) -> BenchmarkDefinition {
    let yaml = std::fs::read_to_string(dir.join("watdiv-stress-mini-tiny.yml"))
        .expect("fixture YAML missing");
    serde_yaml::from_str(&yaml).expect("fixture YAML malformed")
}

fn load_expected(dir: &Path) -> HashMap<String, usize> {
    let json = std::fs::read_to_string(dir.join("expected.json")).expect("expected.json missing");
    serde_json::from_str(&json).expect("expected.json malformed")
}

#[test]
fn watdiv_mini_cardinalities_match() {
    let dir = artifacts_dir();
    let bench = load_yaml(&dir);
    let expected = load_expected(&dir);

    let mut relations: BTreeMap<String, TreeTrie> = BTreeMap::new();
    for rel in &bench.relations {
        let path = dir.join(format!("{}.parquet", rel.name));
        let trie = TreeTrie::from_parquet(&path)
            .unwrap_or_else(|e| panic!("failed to load {path:?}: {e}"));
        relations.insert(rel.name.clone(), trie);
    }

    for q in &bench.queries {
        let key = format!("{}::{}", bench.name, q.name);
        let want = *expected
            .get(&key)
            .unwrap_or_else(|| panic!("no expected entry for {key}"));

        let parsed: JoinQuery = q.query.parse().expect("datalog parse failure");
        let got =
            lftj_join::<TreeTrie, LeapfrogTriejoin>(&relations, parsed, &LexicographicOptimiser)
                .len();

        assert_eq!(
            got, want,
            "cardinality mismatch on {key}: got {got}, expected {want}\nquery: {}",
            q.query
        );
    }
}
