name: Build and Test master

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  RUST_BACKTRACE: 1

jobs:

  build:
    name: Build Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - run: cargo build --verbose

  test:
    name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: nightly, os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
      - run: cargo test --verbose

  publish:

    if: github.repository == 'aidan-bailey/kermit'

    needs: test
  
    runs-on: ubuntu-latest

    name: 'publish'

    environment: cargo

    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: "/kermit/"
            tag_prefix: "kermit"
          - dir: "/kermit-algos/"
            tag_prefix: "kermit-algos"
          - dir: "/kermit-ds/"
            tag_prefix: "kermit-ds"
          - dir: "/kermit-iters/"
            tag_prefix: "kermit-iters"
          - dir: "/kermit-kvs/"
            tag_prefix: "kermit-kvs"

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          DIR: ${{ matrix.dir }}
          TAG_PREFIX: ${{ matrix.tag_prefix }}
