name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: master-${{ github.sha }}
  cancel-in-progress: false

env:
  RUST_BACKTRACE: 1

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@ad397744b0d591a723ab90405b7247fac0e6b8db # v2
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --verbose
        env:
          RUSTFLAGS: -Dwarnings
      - run: cargo test --verbose
      - run: cargo doc --workspace
        env:
          RUSTFLAGS: -Dwarnings
          RUSTDOCFLAGS: -Dwarnings
