name: CI PR

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  MIRIFLAGS: "-Zmiri-disable-isolation"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
      - run: cargo test --verbose

  clippy:
    name: Lint with clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
          rust-version: nightly
      - run: cargo clippy --all-targets --verbose

  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          components: rustfmt
          rust-version: nightly
      - run: cargo fmt --all -- --check

  doc:
    name: Verify crate documentation
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: nightly
      - run: cargo doc --workspace

  miri:
    name: Check for undefined behaviour with miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hecrj/setup-rust-action@v2
        with:
          components: miri
          rust-version: nightly
      - run: cargo miri setup
      - run: cargo miri test
